GET http://localhost:8080/comments?movieId=1
Accept: application/json

###

POST http://localhost:8080/comments?movieId=1
Content-Type: application/json
X-Account-Id: 1
X-Account: bar

{
  "content": "test comment here"
}

###

PUT http://localhost:8080/comments/17
Content-Type: application/json
X-Account-Id: 1
X-Account: bar

{
  "content": "updated test comment"
}

###

POST http://localhost:8080/comments/17/like?liked=false
Content-Type: application/json
X-Account-Id: 1
X-Account: bar

###

DELETE http://localhost:8080/comments/17
Content-Type: application/json
X-Account-Id: 1
X-Account: bar

###
