GET http://localhost:8080/movies?title=t&offset=0&limit=100
Accept: application/json

###

GET http://localhost:8080/movies/2
Accept: application/json
X-Account-Id: 1
X-Account: bar

###

POST http://localhost:8080/movies/1/like
Accept: application/json
X-Account-Id: 1
X-Account: bar

###