GET http://localhost:8083/movies?offset=0&limit=100&title=Avengers
Accept: application/json

###

GET http://localhost:8083/movies/99861
Accept: application/json
X-Account-Id: 1
X-Account: bar

###

POST http://localhost:8083/movies/1/like
Accept: application/json
X-Account-Id: 1
X-Account: bar

###

GET http://localhost:8083/trending
Accept: application/json

###
